after-startup-command = [
  'exec-and-forget borders active_color=0xee33ccff inactive_color=0xaa595959 width=5.0'
]
start-at-login = true
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

[gaps]
inner.horizontal = 8
inner.vertical =   8
outer.left =       5
outer.bottom =     5
outer.top =        5
outer.right =      5

[[on-window-detected]]
if.app-id = 'com.spotify.client'
run = 'move-node-to-workspace 2'
[[on-window-detected]]
if.window-title-regex-substring = '.*gmail.*'
run = 'move-node-to-workspace 2'

[mode.main.binding]
# alt-enter = 'exec-and-forget open -n /System/Applications/Utilities/Terminal.app'
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# See: https://nikitabobko.github.io/AeroSpace/commands#move
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

alt-shift-n = 'resize smart -50'
alt-shift-m = 'resize smart +50'

ctrl-alt-1 = 'workspace 1'
ctrl-alt-2 = 'workspace 2'
ctrl-alt-3 = 'workspace 3'
ctrl-alt-4 = 'workspace 4'
ctrl-alt-5 = 'workspace 5'
ctrl-alt-shift-1 = 'move-node-to-workspace 1'
ctrl-alt-shift-2 = 'move-node-to-workspace 2'
ctrl-alt-shift-3 = 'move-node-to-workspace 3'
ctrl-alt-shift-4 = 'move-node-to-workspace 4'
ctrl-alt-shift-5 = 'move-node-to-workspace 5'

alt-r = 'mode resize'
alt-shift-semicolon = 'mode service'
alt-shift-comma = 'layout tiles horizontal vertical'

alt-tab = 'workspace-back-and-forth'
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

ctrl-alt-shift-h = ['join-with left', 'mode main']
ctrl-alt-shift-j = ['join-with down', 'mode main']
ctrl-alt-shift-k = ['join-with up', 'mode main']
ctrl-alt-shift-l = ['join-with right', 'mode main']
[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layout
f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
backspace = ['close-all-windows-but-current', 'mode main']

[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
enter = 'mode main'
esc = 'mode main'

