#!/bin/bash

source "$CONFIG_DIR/icons.sh" # Loads all defined icons

ITEM_DIR="$CONFIG_DIR/items" # Directory where the items are configured
PLUGIN_DIR="$CONFIG_DIR/plugins" # Directory where all the plugin scripts are stored

FONT="VictorMono Nerd Font" # Needs to have Regular, Bold, Semibold, Heavy and Black variants
PADDINGS=3 # All paddings use this value (icon, label, background)

BUBBLE_BG=0xaa95ada3
BUBBLE_INACTIVE_BG=0xff78abab
BUBBLE_ACTIVE_BG=0xaa399999
TEXT=0xfffafbfb
DARK=0xcc232323

# aerospace setting
AEROSPACE_FOCUSED_MONITOR_NO=$(aerospace list-workspaces --focused)
AEROSPACE_LIST_OF_WINDOWS_IN_FOCUSED_MONITOR=$(aerospace list-windows --workspace $AEROSPACE_FOCUSED_MONITOR_NO | awk -F'|' '{gsub(/^ *| *$/, "", $2); print $2}')

hostname=$(hostname)
if [ "$hostname" = "Vincents-MBP-2" ]; then
  padding_right=1550
  padding_left=1550
else
  padding_right=20
  padding_left=20
fi

bar=(
  height=26
  color=0x00000000
  border_width=0
  position=top
  sticky=on
  padding_right=$padding_right
  padding_left=$padding_left
  topmost=window
)

sketchybar --bar "${bar[@]}"

# Setting up default values
defaults=(
  updates=when_shown
  icon.font="$FONT:Regular:14.0"
  icon.color=0xFFFFFFFF
  label.font="$FONT:Semibold:13.0"
  scroll_texts=on
  background.color=0x00000000
)

sketchybar --default "${defaults[@]}"


# Left
source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"

source "$ITEM_DIR/front_app.sh"
source "$ITEM_DIR/weather.sh"
source "$ITEM_DIR/spotify.sh"

# source "$ITEM_DIR/spotify.sh"

# Right
source "$ITEM_DIR/time.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/wifi.sh"
source "$ITEM_DIR/volume.sh"
# source "$ITEM_DIR/svim.sh"

sketchybar --hotload on

# Forcing all item scripts to run (never do this outside of sketchybarrc)
sketchybar --update

echo "sketchybar configuation loaded.."

